title: CileServer Documentation
description: Documentation for CileServer
theme: just-the-docs
url: "https://phneutral26.github.io/cileserver"

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "GitHub":
    - "//github.com/phneutral26/cileserver"

# Color scheme currently only supports "dark" or nil (default)
color_scheme: dark

# Footer content
footer_content: "Copyright &copy; 2025 CileServer. Distributed under the MIT License."

# Enable or disable heading anchors
heading_anchors: true

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "GitHub":
    - "//github.com/phneutral26/cileserver"

# Color scheme currently only supports "dark" or nil (default)
color_scheme: dark

# Footer content
footer_content: "Copyright &copy; 2025 CileServer. Distributed under the MIT License."

# Enable or disable heading anchors
heading_anchors: true 