title: Documentation
description: Documentation for CileServer
theme: just-the-docs
url: "https://phneutral26.github.io/cileserver"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "GitHub":
    - "//github.com/phneutral26/cileserver"

# Color scheme currently only supports "dark" or nil (default)
color_scheme: dark

# Footer content
footer_content: "Copyright &copy; 2024 CileServer. Distributed under the MIT License."

# Enable or disable heading anchors
heading_anchors: true

# Collections
collections:
  docs:
    output: true
    permalink: /:path/

# Default values
defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: default
      search: true
      toc: true
      toc_heading: "On this page"
      toc_min: 2
      toc_max: 3 