title: CileServer Documentation
description: Documentation for CileServer
theme: minima
url: "https://phneutral26.github.io/cileserver"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "GitHub":
    - "//github.com/phneutral26/cileserver"

# Footer content
footer_content: "Copyright &copy; 2025 CileServer. Distributed under the MIT License."

# Enable or disable heading anchors
heading_anchors: true 